use_frameworks!

platform :ios, '8.0'

target 'DataStruct_Example' do
  pod 'DataStruct', :path => '../'

  target 'DataStruct_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
